export const labelUtils = {
  defaultPolicy: 'Default Policy',

  /* ----------------------------------------Tankhwa Patra---------------------------------------- */

  // pfNumber: 'PF Number',
  // pfJoiningDate: 'PF Joining Date',
  // pfBank: 'PF Bank',
  // pfBankIFSCCode: 'PF Bank IFSC Code',
  // pfBankAccountNumber: 'PF Bank Account Number',
  // esicNumber: 'ESIC Number',
  // esicJoiningDate: 'ESIC Joining Date',
  // esicEndMonth: 'ESIC End Month',
  // salaryCalculationAct: 'Salary Calculation ACT',
  // aadharCardNumber: 'Aadhar Card No',
  // nameOnAadhar: 'Name (As On Aadhar Card )',
  // viewAadhar: 'View Aadhar',
  // showBankBranch: false,
  // bankIfscCodeLabel: 'Bank Ifsc Code',
  // tankhwaPatraNameLabel: 'Tankhwa Patra',
  // showUanNumber: true,
  // showpfbankAccountNo: true,
  // showPanCard: true,
  // showpfbankMasterID: true,
  // showpfbankIFSC: true,
  // showesicEndMonth: true,
  // confirmLabel: 'Confirm',
  // RetainerLabel: '',
  // VisitingConsultantLabel: '',
  // copyRightYear: '2022',
  // othernumberLabel: 'Other Contact Number',
  // showCountryCodeSelected: true,
  // shopActLabel: 'Shop Act',
  // factoryActLabel: 'Factory Act',
  // houseNumberLabel: 'House No.',
  // houseNameLabel: 'House Name',
  // landMarkLabel: 'LandMark',
  // zipCodeLabel: 'Zip Code',
  // areaLabel: 'Area',
  // stateLabel: 'State',
  // districtLabel: 'District',
  // showDistrict: false,
  // LoginPageLabel: 'Mobile Number',
  // EmployementType: ['Probation', 'Trainee', 'Confirm', 'Apprenticeship', 'Contract', 'Locum'],
  // pihMobileNumber: false,
  // payrollFrequencyType: ['Monthly', 'Fortnightly', 'Weekly'],
  // showPayrollFrequency: false,
  // showExpensePurpose: true,
  // validateAadharNumber: true,
  // validatePanNumber: true,
  // showGenerateExpenseVoucher: false,

  /* ----------------------------------------Pacific International Hospital ( PIH )---------------------------------------- */

  // tankhwaPatraNameLabel: 'Pacific International Hospital',
  // pfNumber: 'NASFUND',
  // pfJoiningDate: 'NASFUND Joining Date',
  // pfBank: 'NASFUND Bank',
  // pfBankIFSCCode: 'NASFUND Bank IFSC Code',
  // pfBankAccountNumber: 'NASFUND Bank Account Number',
  // esicNumber: 'NCSL Number',
  // esicJoiningDate: 'NCSL Joining Date',
  // esicEndMonth: 'NCSL End Month',
  // salaryCalculationAct: 'Overtime Governing Terms',
  // aadharCardNumber: 'National I’D No',
  // nameOnAadhar: 'Name (As On National I’D )',
  // viewAadhar: 'View National I’D',
  // showBankBranch: true,
  // bankIfscCodeLabel: 'BSB Code',
  // showUanNumber: false,
  // showpfbankAccountNo: false,
  // showPanCard: false,
  // showpfbankMasterID: false,
  // showpfbankIFSC: false,
  // showesicEndMonth: false,
  // confirmLabel: 'Permanent',
  // RetainerLabel: 'Retainer',
  // VisitingConsultantLabel: 'Visiting Consultant',
  // copyRightYear: '2024',
  // othernumberLabel: 'Emergency Contact Number',
  // showCountryCodeSelected: false,
  // shopActLabel: 'Contract',
  // factoryActLabel: ' Employment Act PNG',
  // houseNumberLabel: 'House No. / Section No.',
  // houseNameLabel: 'House Name / Lot No.',
  // landMarkLabel: 'Landmark / Street Name',
  // zipCodeLabel: 'PO Box No.',
  // areaLabel: 'Ward / LLG',
  // stateLabel: 'State / Province',
  // districtLabel: 'Suburb / District',
  // showDistrict: true,
  // LoginPageLabel: 'Mobile Number / Employee Code',
  // EmployementType:['Probation', 'Trainee', 'Permanent', 'Apprenticeship', 'Locum','Retainer', 'Visiting Consultant', 'Contract'],
  // pihMobileNumber: true
  // showPayrollFrequency: true,
  // showExpensePurpose: true,
  // validateAadharNumber: false,
  // validatePanNumber: false,
  // showGenerateExpenseVoucher: false,

  /* ---------------------------------------- MARS ---------------------------------------- */

  // pfNumber: 'PF Number',
  // pfJoiningDate: 'PF Joining Date',
  // pfBank: 'PF Bank',
  // pfBankIFSCCode: 'PF Bank IFSC Code',
  // pfBankAccountNumber: 'PF Bank Account Number',
  // esicNumber: 'ESIC Number',
  // esicJoiningDate: 'ESIC Joining Date',
  // esicEndMonth: 'ESIC End Month',
  // salaryCalculationAct: 'Salary Calculation ACT',
  // aadharCardNumber: 'Aadhar Card No',
  // nameOnAadhar: 'Name (As On Aadhar Card )',
  // viewAadhar: 'View Aadhar',
  // showBankBranch: false,
  // bankIfscCodeLabel: 'Bank Ifsc Code',
  // tankhwaPatraNameLabel: 'Mars Consultancy',
  // showUanNumber: true,
  // showpfbankAccountNo: true,
  // showPanCard: true,
  // showpfbankMasterID: true,
  // showpfbankIFSC: true,
  // showesicEndMonth: true,
  // confirmLabel: 'Confirm',
  // RetainerLabel: '',
  // VisitingConsultantLabel: '',
  // copyRightYear: '2022',
  // othernumberLabel: 'Other Contact Number',
  // showCountryCodeSelected: true,
  // shopActLabel: 'Shop Act',
  // factoryActLabel: 'Factory Act',
  // houseNumberLabel: 'House No.',
  // houseNameLabel: 'House Name',
  // landMarkLabel: 'LandMark',
  // zipCodeLabel: 'Zip Code',
  // areaLabel: 'Area',
  // stateLabel: 'State',
  // districtLabel: 'District',
  // showDistrict: false,
  // LoginPageLabel: 'Mobile Number',
  // EmployementType: ['Probation', 'Trainee', 'Confirm', 'Apprenticeship', 'Contract', 'Locum'],
  // pihMobileNumber: false,
  // payrollFrequencyType: ['Monthly', 'Fortnightly', 'Weekly'],
  // showPayrollFrequency: false,
  // showExpensePurpose: false,
  // validateAadharNumber: true,
  // validatePanNumber: true,
  // showGenerateExpenseVoucher: true,

  /* ---------------------------------------- AKAR ---------------------------------------- */

  pfNumber: 'PF Number',
  pfJoiningDate: 'PF Joining Date',
  pfBank: 'PF Bank',
  pfBankIFSCCode: 'PF Bank IFSC Code',
  pfBankAccountNumber: 'PF Bank Account Number',
  esicNumber: 'ESIC Number',
  esicJoiningDate: 'ESIC Joining Date',
  esicEndMonth: 'ESIC End Month',
  salaryCalculationAct: 'Salary Calculation ACT',
  aadharCardNumber: 'Aadhar Card No',
  nameOnAadhar: 'Name (As On Aadhar Card )',
  viewAadhar: 'View Aadhar',
  showBankBranch: false,
  bankIfscCodeLabel: 'Bank Ifsc Code',
  // Neutral product-agnostic term. This one value drives the footer, data
  // column headers ("SN Code"), form labels and Excel export headers.
  tankhwaPatraNameLabel: 'SN',
  showUanNumber: true,
  showpfbankAccountNo: true,
  showPanCard: true,
  showpfbankMasterID: true,
  showpfbankIFSC: true,
  showesicEndMonth: true,
  confirmLabel: 'Confirm',
  RetainerLabel: '',
  VisitingConsultantLabel: '',
  copyRightYear: '2022',
  othernumberLabel: 'Other Contact Number',
  showCountryCodeSelected: true,
  shopActLabel: 'Shop Act',
  factoryActLabel: 'Factory Act',
  houseNumberLabel: 'House No.',
  houseNameLabel: 'House Name',
  landMarkLabel: 'LandMark',
  zipCodeLabel: 'Zip Code',
  areaLabel: 'Area',
  stateLabel: 'State',
  districtLabel: 'District',
  showDistrict: false,
  LoginPageLabel: 'Mobile Number',
  EmployementType: ['Probation', 'Trainee', 'Confirm', 'Apprenticeship', 'Contract', 'Locum'],
  pihMobileNumber: false,
  payrollFrequencyType: ['Monthly', 'Fortnightly', 'Weekly'],
  showPayrollFrequency: false,
  showExpensePurpose: true,
  validateAadharNumber: true,
  validatePanNumber: true,
  showGenerateExpenseVoucher: false,
  /* ----------------------------------------Harsha Engineering---------------------------------------- */

  // pfNumber: 'PF Number',
  // pfJoiningDate: 'PF Joining Date',
  // pfBank: 'PF Bank',
  // pfBankIFSCCode: 'PF Bank IFSC Code',
  // pfBankAccountNumber: 'PF Bank Account Number',
  // esicNumber: 'ESIC Number',
  // esicJoiningDate: 'ESIC Joining Date',
  // esicEndMonth: 'ESIC End Month',
  // salaryCalculationAct: 'Salary Calculation ACT',
  // aadharCardNumber: 'Aadhar Card No',
  // nameOnAadhar: 'Name (As On Aadhar Card )',
  // viewAadhar: 'View Aadhar',
  // showBankBranch: false,
  // bankIfscCodeLabel: 'Bank Ifsc Code',
  // tankhwaPatraNameLabel: 'Harsha Engineering',
  // showUanNumber: true,
  // showpfbankAccountNo: true,
  // showPanCard: true,
  // showpfbankMasterID: true,
  // showpfbankIFSC: true,
  // showesicEndMonth: true,
  // confirmLabel: 'Confirm',
  // RetainerLabel: '',
  // VisitingConsultantLabel: '',
  // copyRightYear: '2022',
  // othernumberLabel: 'Other Contact Number',
  // showCountryCodeSelected: true,
  // shopActLabel: 'Shop Act',
  // factoryActLabel: 'Factory Act',
  // houseNumberLabel: 'House No.',
  // houseNameLabel: 'House Name',
  // landMarkLabel: 'LandMark',
  // zipCodeLabel: 'Zip Code',
  // areaLabel: 'Area',
  // stateLabel: 'State',
  // districtLabel: 'District',
  // showDistrict: false,
  // LoginPageLabel: 'Mobile Number',
  // EmployementType: ['Probation', 'Trainee', 'Confirm', 'Apprenticeship', 'Contract', 'Locum'],
  // pihMobileNumber: false,
  // payrollFrequencyType: ['Monthly', 'Fortnightly', 'Weekly'],
  // showPayrollFrequency: false,
  // showExpensePurpose: true,
  // validateAadharNumber: true,
  // validatePanNumber: true,
  // showGenerateExpenseVoucher: false,

};
