import { UserRole } from '../app/shared/auth.roles';

export const environment = {
  production: true,
  buyUrl: 'https://1.envato.market/6NV1b',
  SCARF_ANALYTICS: false,
  adminRoot: '/app',
  apiUrl: 'https://api.staging.example.invalid/',
  biometricApiUrl: 'https://biometric.staging.example.invalid/',
  chatUrl: 'https://chat.staging.example.invalid',
  appUrl: 'https://staging.example.invalid/#/user/preboarding/',
  appUrl1: 'https://staging.example.invalid/#/user/submitform/',
  appUrl2: 'https://staging.example.invalid/#/user/jobPosting/',
  appUrl3: 'https://staging.example.invalid/#/user/applyJob/',
  appLoginUrl: 'https://staging.example.invalid/',
  defaultMenuType: 'menu-default',
  subHiddenBreakpoint: 1440,
  menuHiddenBreakpoint: 768,
  themeColorStorageKey: 'hrms-themecolor-v2',
  defaultColor: 'light.tealslate',
  isMultiColorActive: false,
  isDarkSwitchActive: true,
  defaultDirection: 'ltr',
  themeRadiusStorageKey: 'vien-themeradius',
  isAuthGuardActive: false,
  defaultRole: UserRole.Admin,
  secretKeyForEncoding: '8d8e2f43a6dbcc7281e2b1f9c8463ab243dfa9ecb541a12a38c9c5671f876c22',
  firebase: {
    apiKey: '',
    authDomain: '',
    databaseURL: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
    measurementId: '',
  },
  mediumDateFormat: 'mediumDate',
  permission: [],
};