import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class NationalityListService {

 Nationality : any [] = [
    { name: "Afghan" },
    { name: "Albanian" },
    { name: "Algerian" },
    { name: "Andorran" },
    { name: "Angolan" },
    { name: "Antiguan or Barbudan" },
    { name: "Argentine" },
    { name: "Armenian" },
    { name: "Australian" },
    { name: "Austrian" },
    { name: "Azerbaijani, Azeri" },
    { name: "Bahamian" },
    { name: "Bahraini" },
    { name: "Bengali" },
    { name: "Barbadian" },
    { name: "Belarusian" },
    { name: "Belgian" },
    { name: "Belizean" },
    { name: "Beninese, Beninois" },
    { name: "Bhutanese" },
    { name: "Bolivian" },
    { name: "Bosnian or Herzegovinian" },
    { name: "Motswana, Botswanan" },
    { name: "Brazilian" },
    { name: "Bruneian" },
    { name: "Bulgarian" },
    { name: "Burkinabé" },
    { name: "Burmese" },
    { name: "Burundian" },
    { name: "Cabo Verdean" },
    { name: "Cambodian" },
    { name: "Cameroonian" },
    { name: "Canadian" },
    { name: "Central African" },
    { name: "Chadian" },
    { name: "Chilean" },
    { name: "Chinese" },
    { name: "Colombian" },
    { name: "Comoran, Comorian" },
    { name: "Congolese" },
    { name: "Congolese" },
    { name: "Costa Rican" },
    { name: "Ivorian" },
    { name: "Croatian" },
    { name: "Cuban" },
    { name: "Cypriot" },
    { name: "Czech" },
    { name: "Danish" },
    { name: "Djiboutian" },
    { name: "Dominican" },
    { name: "Dominican" },
    { name: "Timorese" },
    { name: "Ecuadorian" },
    { name: "Egyptian" },
    { name: "Salvadoran" },
    { name: "Equatorial Guinean, Equatoguinean" },
    { name: "Eritrean" },
    { name: "Estonian" },
    { name: "Ethiopian" },
    { name: "Fijian" },
    { name: "Finnish" },
    { name: "French" },
    { name: "Gabonese" },
    { name: "Gambian" },
    { name: "Georgian" },
    { name: "German" },
    { name: "Ghanaian" },
    { name: "Gibraltar" },
    { name: "Greek, Hellenic" },
    { name: "Grenadian" },
    { name: "Guatemalan" },
    { name: "Guinean" },
    { name: "Bissau-Guinean" },
    { name: "Guyanese" },
    { name: "Haitian" },
    { name: "Honduran" },
    { name: "Hungarian, Magyar" },
    { name: "Icelandic" },
    { name: "Indian" },
    { name: "Indonesian" },
    { name: "Iranian, Persian" },
    { name: "Iraqi" },
    { name: "Irish" },
    { name: "Israeli" },
    { name: "Italian" },
    { name: "Ivorian" },
    { name: "Jamaican" },
    { name: "Japanese" },
    { name: "Jordanian" },
    { name: "Kazakhstani, Kazakh" },
    { name: "Kenyan" },
    { name: "I-Kiribati" },
    { name: "North Korean" },
    { name: "South Korean" },
    { name: "Kuwaiti" },
    { name: "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz" },
    { name: "Lao, Laotian" },
    { name: "Latvian, Lettish" },
    { name: "Lebanese" },
    { name: "Basotho" },
    { name: "Liberian" },
    { name: "Libyan" },
    { name: "Liechtensteiner" },
    { name: "Lithuanian" },
    { name: "Luxembourg, Luxembourgish" },
    { name: "Macedonian" },
    { name: "Malagasy" },
    { name: "Malawian" },
    { name: "Malaysian" },
    { name: "Maldivian" },
    { name: "Malian, Malinese" },
    { name: "Maltese" },
    { name: "Marshallese" },
    { name: "Martiniquais, Martinican" },
    { name: "Mauritanian" },
    { name: "Mauritian" },
    { name: "Mexican" },
    { name: "Micronesian" },
    { name: "Moldovan" },
    { name: "Monégasque, Monacan" },
    { name: "Mongolian" },
    { name: "Montenegrin" },
    { name: "Moroccan" },
    { name: "Mozambican" },
    { name: "Namibian" },
    { name: "Nauruan" },
    { name: "Nepali" },
    { name: "Dutch, Netherlandic" },
    { name: "New Zealand, NZ, Zelanian" },
    { name: "Nicaraguan" },
    { name: "Nigerien" },
    { name: "Nigerian" },
    { name: "Northern Marianan" },
    { name: "Norwegian" },
    { name: "Omani" },
    { name: "Pakistani" },
    { name: "Palauan" },
    { name: "Palestinian" },
    { name: "Panamanian" },
    { name: "Papua New Guinean, Papuan" },
    { name: "Paraguayan" },
    { name: "Peruvian" },
    { name: "Filipino, Philippine" },
    { name: "Polish" },
    { name: "Portuguese" },
    { name: "Puerto Rican" },
    { name: "Qatari" },
    { name: "Romanian" },
    { name: "Russian" },
    { name: "Rwandan" },
    { name: "Kittitian or Nevisian" },
    { name: "Saint Lucian" },
    { name: "Saint Vincentian, Vincentian" },
    { name: "Samoan" },
    { name: "Sammarinese" },
    { name: "São Toméan" },
    { name: "Saudi, Saudi Arabian" },
    { name: "Senegalese" },
    { name: "Serbian" },
    { name: "Seychellois" },
    { name: "Sierra Leonean" },
    { name: "Singapore, Singaporean" },
    { name: "Slovak" },
    { name: "Slovenian, Slovene" },
    { name: "Solomon Island" },
    { name: "Somali" },
    { name: "South African" },
    { name: "South Sudanese" },
    { name: "Spanish" },
    { name: "Sri Lankan" },
    { name: "Sudanese" },
    { name: "Surinamese" },
    { name: "Swazi" },
    { name: "Swedish" },
    { name: "Swiss" },
    { name: "Syrian" },
    { name: "Tajikistani" },
    { name: "Tanzanian" },
    { name: "Thai" },
    { name: "Timorese" },
    { name: "Togolese" },
    { name: "Tokelauan" },
    { name: "Tongan" },
    { name: "Trinidadian or Tobagonian" },
    { name: "Tunisian" },
    { name: "Turkish" },
    { name: "Turkmen" },
    { name: "Tuvaluan" },
    { name: "Ugandan" },
    { name: "Ukrainian" },
    { name: "Emirati, Emirian, Emiri" },
    { name: "UK, British" },
    { name: "United States, U.S., American" },
    { name: "Uruguayan" },
    { name: "Uzbekistani, Uzbek" },
    { name: "Ni-Vanuatu, Vanuatuan" },
    { name: "Vatican" },
    { name: "Venezuelan" },
    { name: "Vietnamese" },
    { name: "Yemeni" },
    { name: "Zambian" },
    { name: "Zimbabwean" },
  ]

  
  constructor() { }


  fetchNationality(): Observable <any>{
    return of(this.Nationality)
  } 
}
